    LIST P=16F877A
    #INCLUDE <P16F877A.INC>
    SAYI1 EQU 0X24
    SAYI2 EQU 0X25
    ORG 0X00
    GOTO MAIN
MAIN
    BANKSEL TRISB
    CLRF TRISB
    BSF TRISD,0
    BANKSEL PORTB
    CLRF PORTB
    CLRF PORTD
    MOVLW D'10'
    MOVWF SAYI1
    MOVLW D'10'
    MOVWF SAYI2
    CLRW
BUTON
    BTFSS PORTD,0
    GOTO BUTON
    GOTO ISLEM
ISLEM
    MOVLW SAYI1
    SUBWF SAYI2
    BTFSS STATUS,Z
    BSF PORTB,0
    BTFSC STATUS,Z
    BSF PORTB,1
    GOTO ISLEM
    END
    
    
